### PR TITLE
GetMember now can navigate up to parents to find members

### PR DESCRIPTION
**Pull request by wellguimaraes**
Also added WithEmptyCollection method, so the user can initialize a collection field without adding anything to it

### CODE REVIEW

**Comment by robsoncastilho** [comment]
1. I don't get the purpose of setting a field belonging to a base type.
2. About "WithEmptyCollection()", I don't get it either. FluentBuilder already initializes all the collections so that none of them are 'null'. (See 'SetDefaultValuesCommand'). 

If I missed something, please post some examples of usage.
Thanks.

**Comment by wellguimaraes** [comment]
**1.** What if I need to build an Employee with an Id or Name?

```
class Person {
    prop Id;
    prop Name;
    prop Whatever;
}

class Employee {
    prop Role;
}
```

**2.** Ok, got it. So the point was that it was not initializing base type fields/props.

**Comment by robsoncastilho** [comment]
You can do that using With(obj => obj.Id, 2) (Id will be set correctly even if it's declared in the base type.)

In the case of setting FIELDs, if it was only for that case of creating a not-null list, that's ok and you solved the problem BUT I still don't see another purpose for now (I don't know what you're trying to achieve).

Sorry but I have no time to spend in the project for a while. I hope I can do that as soon as possible (there are some features that I'd like to do to ease the usage of mocks and stubs). If you want to help...

Anyway, I'll merge the code and publish a new version on NuGet.
Thanks.

**Comment by wellguimaraes** [comment]
I also expected that behavior, but it simply didn't work for base props/fields. =(
When you have a milestone defined for the next version, let me know, maybe I can help you with that.
Anyway, thanks for merging this pull request.

**Pull request merged**
